#include <genesis.h>

#ifndef _RES_GAUGE_ASSETS_H_
#define _RES_GAUGE_ASSETS_H_

extern const TileSet gauge_h_straight_yellow_strip;
extern const TileSet gauge_v_straight_yellow_strip;
extern const TileSet gauge_h_bevel_yellow_strip_trail;
extern const TileSet gauge_h_bevel_yellow_strip_end;
extern const TileSet gauge_h_bevel_yellow_strip_break;
extern const TileSet gauge_h_straight_small_blue_strip;
extern const TileSet gauge_h_bevel_blue_strip_break;
extern const TileSet gauge_h_bevel_blue_strip_end;
extern const TileSet gauge_h_bevel_blue_strip_trail;
extern const TileSet gauge_h_bevel_blue_to_yellow_strip_bridge;
extern const TileSet gauge_h_bevel_lightblue_strip_break;
extern const TileSet gauge_h_bevel_lightblue_strip_end;
extern const TileSet gauge_h_bevel_lightblue_strip_trail;
extern const TileSet gauge_h_bevel_lightblue_to_blue_strip_bridge;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_end_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_strip_trail;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_strip_break;
extern const TileSet gauge_h_bevel_yellow_with_border_strip_break;
extern const TileSet gauge_h_bevel_yellow_with_border_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_strip_trail;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_blink_off_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_end_blink_off_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_blink_off_strip_trail;
extern const TileSet gauge_h_bevel_yellow_with_border_cap_start_blink_off_strip_break;
extern const TileSet gauge_h_bevel_yellow_with_border_blink_off_strip_break;
extern const TileSet gauge_h_bevel_yellow_with_border_blink_off_strip_end;
extern const TileSet gauge_h_bevel_yellow_with_border_blink_off_strip_trail;
extern const TileSet gauge_h_bevel_blue_with_border_strip_break;
extern const TileSet gauge_h_bevel_blue_with_border_strip_end;
extern const TileSet gauge_h_bevel_blue_with_border_strip_trail;
extern const TileSet gauge_h_bevel_yellow_to_blue_with_border_strip_bridge;
extern const TileSet gauge_h_bevel_blue_to_yellow_with_border_strip_bridge;
extern const TileSet gauge_h_bevel_blue_with_border_blink_off_strip_break;
extern const TileSet gauge_h_bevel_blue_with_border_blink_off_strip_end;
extern const TileSet gauge_h_bevel_blue_with_border_blink_off_strip_trail;
extern const TileSet gauge_h_bevel_yellow_to_blue_with_border_blink_off_strip_bridge;
extern const TileSet gauge_h_bevel_blue_to_yellow_with_border_blink_off_strip_bridge;
extern const TileSet gauge_h_straight_blue_strip;
extern const TileSet gauge_v_straight_blue_strip;
extern const TileSet gauge_h_straight_lightblue_strip;
extern const TileSet gauge_v_straight_lightblue_strip;
extern const Palette gauge_palette;

#endif // _RES_GAUGE_ASSETS_H_
